import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div className='bg-green-300'>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <h1 className=''>
          Welcome to Pokemon World!
        </h1>


        <div className=''>


        </div>
      </main>

      <footer className=''>
        <span>Built by Emmanuel</span>
      </footer>
    </div>
  )
}

export default Home
